#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jardines.modelo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RegistroICBF")]
	public partial class ORMDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertAcudiente(Acudiente instance);
    partial void UpdateAcudiente(Acudiente instance);
    partial void DeleteAcudiente(Acudiente instance);
    partial void InsertAsistencia(Asistencia instance);
    partial void UpdateAsistencia(Asistencia instance);
    partial void DeleteAsistencia(Asistencia instance);
    partial void InsertAvanceAcademico(AvanceAcademico instance);
    partial void UpdateAvanceAcademico(AvanceAcademico instance);
    partial void DeleteAvanceAcademico(AvanceAcademico instance);
    partial void InsertCumpleaños(Cumpleaños instance);
    partial void UpdateCumpleaños(Cumpleaños instance);
    partial void DeleteCumpleaños(Cumpleaños instance);
    partial void InsertJardin(Jardin instance);
    partial void UpdateJardin(Jardin instance);
    partial void DeleteJardin(Jardin instance);
    partial void InsertMadreComunitaria(MadreComunitaria instance);
    partial void UpdateMadreComunitaria(MadreComunitaria instance);
    partial void DeleteMadreComunitaria(MadreComunitaria instance);
    partial void InsertNiño(Niño instance);
    partial void UpdateNiño(Niño instance);
    partial void DeleteNiño(Niño instance);
    partial void InsertReporteInasistenciasEnfermedad(ReporteInasistenciasEnfermedad instance);
    partial void UpdateReporteInasistenciasEnfermedad(ReporteInasistenciasEnfermedad instance);
    partial void DeleteReporteInasistenciasEnfermedad(ReporteInasistenciasEnfermedad instance);
    partial void InsertReporteJardinesNoAprobados(ReporteJardinesNoAprobados instance);
    partial void UpdateReporteJardinesNoAprobados(ReporteJardinesNoAprobados instance);
    partial void DeleteReporteJardinesNoAprobados(ReporteJardinesNoAprobados instance);
    partial void InsertReporteNiñosPorJardin(ReporteNiñosPorJardin instance);
    partial void UpdateReporteNiñosPorJardin(ReporteNiñosPorJardin instance);
    partial void DeleteReporteNiñosPorJardin(ReporteNiñosPorJardin instance);
    partial void InsertReporteSemanalAsistencia(ReporteSemanalAsistencia instance);
    partial void UpdateReporteSemanalAsistencia(ReporteSemanalAsistencia instance);
    partial void DeleteReporteSemanalAsistencia(ReporteSemanalAsistencia instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    #endregion
		
		public ORMDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ORMDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ORMDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ORMDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Acudiente> Acudiente
		{
			get
			{
				return this.GetTable<Acudiente>();
			}
		}
		
		public System.Data.Linq.Table<Asistencia> Asistencia
		{
			get
			{
				return this.GetTable<Asistencia>();
			}
		}
		
		public System.Data.Linq.Table<AvanceAcademico> AvanceAcademico
		{
			get
			{
				return this.GetTable<AvanceAcademico>();
			}
		}
		
		public System.Data.Linq.Table<Cumpleaños> Cumpleaños
		{
			get
			{
				return this.GetTable<Cumpleaños>();
			}
		}
		
		public System.Data.Linq.Table<Jardin> Jardin
		{
			get
			{
				return this.GetTable<Jardin>();
			}
		}
		
		public System.Data.Linq.Table<MadreComunitaria> MadreComunitaria
		{
			get
			{
				return this.GetTable<MadreComunitaria>();
			}
		}
		
		public System.Data.Linq.Table<Niño> Niño
		{
			get
			{
				return this.GetTable<Niño>();
			}
		}
		
		public System.Data.Linq.Table<ReporteInasistenciasEnfermedad> ReporteInasistenciasEnfermedad
		{
			get
			{
				return this.GetTable<ReporteInasistenciasEnfermedad>();
			}
		}
		
		public System.Data.Linq.Table<ReporteJardinesNoAprobados> ReporteJardinesNoAprobados
		{
			get
			{
				return this.GetTable<ReporteJardinesNoAprobados>();
			}
		}
		
		public System.Data.Linq.Table<ReporteNiñosPorJardin> ReporteNiñosPorJardin
		{
			get
			{
				return this.GetTable<ReporteNiñosPorJardin>();
			}
		}
		
		public System.Data.Linq.Table<ReporteSemanalAsistencia> ReporteSemanalAsistencia
		{
			get
			{
				return this.GetTable<ReporteSemanalAsistencia>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuario
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Acudiente")]
	public partial class Acudiente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Identificacion;
		
		private string _Nombre;
		
		private string _Cedula;
		
		private string _Telefono;
		
		private string _Celular;
		
		private string _Direccion;
		
		private string _Correo;
		
		private EntitySet<Niño> _Niño;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdentificacionChanging(int value);
    partial void OnIdentificacionChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnCedulaChanging(string value);
    partial void OnCedulaChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnCelularChanging(string value);
    partial void OnCelularChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    #endregion
		
		public Acudiente()
		{
			this._Niño = new EntitySet<Niño>(new Action<Niño>(this.attach_Niño), new Action<Niño>(this.detach_Niño));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identificacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Identificacion
		{
			get
			{
				return this._Identificacion;
			}
			set
			{
				if ((this._Identificacion != value))
				{
					this.OnIdentificacionChanging(value);
					this.SendPropertyChanging();
					this._Identificacion = value;
					this.SendPropertyChanged("Identificacion");
					this.OnIdentificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(20)")]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this.OnCedulaChanging(value);
					this.SendPropertyChanging();
					this._Cedula = value;
					this.SendPropertyChanged("Cedula");
					this.OnCedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(20)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="VarChar(20)")]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this.OnCelularChanging(value);
					this.SendPropertyChanging();
					this._Celular = value;
					this.SendPropertyChanged("Celular");
					this.OnCelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(100)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(100)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Acudiente_Niño", Storage="_Niño", ThisKey="Identificacion", OtherKey="IdentificadorAcudiente")]
		public EntitySet<Niño> Niño
		{
			get
			{
				return this._Niño;
			}
			set
			{
				this._Niño.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Niño(Niño entity)
		{
			this.SendPropertyChanging();
			entity.Acudiente = this;
		}
		
		private void detach_Niño(Niño entity)
		{
			this.SendPropertyChanging();
			entity.Acudiente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Asistencia")]
	public partial class Asistencia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _IdentificacionNiño;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private string _Estado;
		
		private EntityRef<Niño> _Niño;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdentificacionNiñoChanging(System.Nullable<int> value);
    partial void OnIdentificacionNiñoChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    #endregion
		
		public Asistencia()
		{
			this._Niño = default(EntityRef<Niño>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdentificacionNiño", DbType="Int")]
		public System.Nullable<int> IdentificacionNiño
		{
			get
			{
				return this._IdentificacionNiño;
			}
			set
			{
				if ((this._IdentificacionNiño != value))
				{
					if (this._Niño.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdentificacionNiñoChanging(value);
					this.SendPropertyChanging();
					this._IdentificacionNiño = value;
					this.SendPropertyChanged("IdentificacionNiño");
					this.OnIdentificacionNiñoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(20)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Niño_Asistencia", Storage="_Niño", ThisKey="IdentificacionNiño", OtherKey="NIUP", IsForeignKey=true)]
		public Niño Niño
		{
			get
			{
				return this._Niño.Entity;
			}
			set
			{
				Niño previousValue = this._Niño.Entity;
				if (((previousValue != value) 
							|| (this._Niño.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Niño.Entity = null;
						previousValue.Asistencia.Remove(this);
					}
					this._Niño.Entity = value;
					if ((value != null))
					{
						value.Asistencia.Add(this);
						this._IdentificacionNiño = value.NIUP;
					}
					else
					{
						this._IdentificacionNiño = default(Nullable<int>);
					}
					this.SendPropertyChanged("Niño");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AvanceAcademico")]
	public partial class AvanceAcademico : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _IdentificacionNiño;
		
		private System.Nullable<int> _AnioEscolar;
		
		private string _Nivel;
		
		private string _Notas;
		
		private string _Descripcion;
		
		private System.Nullable<System.DateTime> _FechaEntregaNota;
		
		private EntityRef<Niño> _Niño;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdentificacionNiñoChanging(System.Nullable<int> value);
    partial void OnIdentificacionNiñoChanged();
    partial void OnAnioEscolarChanging(System.Nullable<int> value);
    partial void OnAnioEscolarChanged();
    partial void OnNivelChanging(string value);
    partial void OnNivelChanged();
    partial void OnNotasChanging(string value);
    partial void OnNotasChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnFechaEntregaNotaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaEntregaNotaChanged();
    #endregion
		
		public AvanceAcademico()
		{
			this._Niño = default(EntityRef<Niño>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdentificacionNiño", DbType="Int")]
		public System.Nullable<int> IdentificacionNiño
		{
			get
			{
				return this._IdentificacionNiño;
			}
			set
			{
				if ((this._IdentificacionNiño != value))
				{
					if (this._Niño.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdentificacionNiñoChanging(value);
					this.SendPropertyChanging();
					this._IdentificacionNiño = value;
					this.SendPropertyChanged("IdentificacionNiño");
					this.OnIdentificacionNiñoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnioEscolar", DbType="Int")]
		public System.Nullable<int> AnioEscolar
		{
			get
			{
				return this._AnioEscolar;
			}
			set
			{
				if ((this._AnioEscolar != value))
				{
					this.OnAnioEscolarChanging(value);
					this.SendPropertyChanging();
					this._AnioEscolar = value;
					this.SendPropertyChanged("AnioEscolar");
					this.OnAnioEscolarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nivel", DbType="VarChar(20)")]
		public string Nivel
		{
			get
			{
				return this._Nivel;
			}
			set
			{
				if ((this._Nivel != value))
				{
					this.OnNivelChanging(value);
					this.SendPropertyChanging();
					this._Nivel = value;
					this.SendPropertyChanged("Nivel");
					this.OnNivelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notas", DbType="VarChar(10)")]
		public string Notas
		{
			get
			{
				return this._Notas;
			}
			set
			{
				if ((this._Notas != value))
				{
					this.OnNotasChanging(value);
					this.SendPropertyChanging();
					this._Notas = value;
					this.SendPropertyChanged("Notas");
					this.OnNotasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(255)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEntregaNota", DbType="Date")]
		public System.Nullable<System.DateTime> FechaEntregaNota
		{
			get
			{
				return this._FechaEntregaNota;
			}
			set
			{
				if ((this._FechaEntregaNota != value))
				{
					this.OnFechaEntregaNotaChanging(value);
					this.SendPropertyChanging();
					this._FechaEntregaNota = value;
					this.SendPropertyChanged("FechaEntregaNota");
					this.OnFechaEntregaNotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Niño_AvanceAcademico", Storage="_Niño", ThisKey="IdentificacionNiño", OtherKey="NIUP", IsForeignKey=true)]
		public Niño Niño
		{
			get
			{
				return this._Niño.Entity;
			}
			set
			{
				Niño previousValue = this._Niño.Entity;
				if (((previousValue != value) 
							|| (this._Niño.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Niño.Entity = null;
						previousValue.AvanceAcademico.Remove(this);
					}
					this._Niño.Entity = value;
					if ((value != null))
					{
						value.AvanceAcademico.Add(this);
						this._IdentificacionNiño = value.NIUP;
					}
					else
					{
						this._IdentificacionNiño = default(Nullable<int>);
					}
					this.SendPropertyChanged("Niño");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cumpleaños")]
	public partial class Cumpleaños : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _IdentificacionNiño;
		
		private System.Nullable<System.DateTime> _FechaCumpleaños;
		
		private string _Descripcion;
		
		private EntityRef<Niño> _Niño;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdentificacionNiñoChanging(System.Nullable<int> value);
    partial void OnIdentificacionNiñoChanged();
    partial void OnFechaCumpleañosChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaCumpleañosChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    #endregion
		
		public Cumpleaños()
		{
			this._Niño = default(EntityRef<Niño>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdentificacionNiño", DbType="Int")]
		public System.Nullable<int> IdentificacionNiño
		{
			get
			{
				return this._IdentificacionNiño;
			}
			set
			{
				if ((this._IdentificacionNiño != value))
				{
					if (this._Niño.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdentificacionNiñoChanging(value);
					this.SendPropertyChanging();
					this._IdentificacionNiño = value;
					this.SendPropertyChanged("IdentificacionNiño");
					this.OnIdentificacionNiñoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCumpleaños", DbType="Date")]
		public System.Nullable<System.DateTime> FechaCumpleaños
		{
			get
			{
				return this._FechaCumpleaños;
			}
			set
			{
				if ((this._FechaCumpleaños != value))
				{
					this.OnFechaCumpleañosChanging(value);
					this.SendPropertyChanging();
					this._FechaCumpleaños = value;
					this.SendPropertyChanged("FechaCumpleaños");
					this.OnFechaCumpleañosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(1)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Niño_Cumpleaños", Storage="_Niño", ThisKey="IdentificacionNiño", OtherKey="NIUP", IsForeignKey=true)]
		public Niño Niño
		{
			get
			{
				return this._Niño.Entity;
			}
			set
			{
				Niño previousValue = this._Niño.Entity;
				if (((previousValue != value) 
							|| (this._Niño.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Niño.Entity = null;
						previousValue.Cumpleaños.Remove(this);
					}
					this._Niño.Entity = value;
					if ((value != null))
					{
						value.Cumpleaños.Add(this);
						this._IdentificacionNiño = value.NIUP;
					}
					else
					{
						this._IdentificacionNiño = default(Nullable<int>);
					}
					this.SendPropertyChanged("Niño");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Jardin")]
	public partial class Jardin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Identificador;
		
		private string _Nombre;
		
		private string _Direccion;
		
		private string _Estado;
		
		private EntitySet<Niño> _Niño;
		
		private EntitySet<ReporteJardinesNoAprobados> _ReporteJardinesNoAprobados;
		
		private EntitySet<ReporteNiñosPorJardin> _ReporteNiñosPorJardin;
		
		private EntitySet<Usuario> _Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdentificadorChanging(int value);
    partial void OnIdentificadorChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    #endregion
		
		public Jardin()
		{
			this._Niño = new EntitySet<Niño>(new Action<Niño>(this.attach_Niño), new Action<Niño>(this.detach_Niño));
			this._ReporteJardinesNoAprobados = new EntitySet<ReporteJardinesNoAprobados>(new Action<ReporteJardinesNoAprobados>(this.attach_ReporteJardinesNoAprobados), new Action<ReporteJardinesNoAprobados>(this.detach_ReporteJardinesNoAprobados));
			this._ReporteNiñosPorJardin = new EntitySet<ReporteNiñosPorJardin>(new Action<ReporteNiñosPorJardin>(this.attach_ReporteNiñosPorJardin), new Action<ReporteNiñosPorJardin>(this.detach_ReporteNiñosPorJardin));
			this._Usuario = new EntitySet<Usuario>(new Action<Usuario>(this.attach_Usuario), new Action<Usuario>(this.detach_Usuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identificador", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Identificador
		{
			get
			{
				return this._Identificador;
			}
			set
			{
				if ((this._Identificador != value))
				{
					this.OnIdentificadorChanging(value);
					this.SendPropertyChanging();
					this._Identificador = value;
					this.SendPropertyChanged("Identificador");
					this.OnIdentificadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(100)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(20)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Jardin_Niño", Storage="_Niño", ThisKey="Identificador", OtherKey="IdentificadorJardin")]
		public EntitySet<Niño> Niño
		{
			get
			{
				return this._Niño;
			}
			set
			{
				this._Niño.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Jardin_ReporteJardinesNoAprobados", Storage="_ReporteJardinesNoAprobados", ThisKey="Identificador", OtherKey="IdentificadorJardin")]
		public EntitySet<ReporteJardinesNoAprobados> ReporteJardinesNoAprobados
		{
			get
			{
				return this._ReporteJardinesNoAprobados;
			}
			set
			{
				this._ReporteJardinesNoAprobados.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Jardin_ReporteNiñosPorJardin", Storage="_ReporteNiñosPorJardin", ThisKey="Identificador", OtherKey="IdentificadorJardin")]
		public EntitySet<ReporteNiñosPorJardin> ReporteNiñosPorJardin
		{
			get
			{
				return this._ReporteNiñosPorJardin;
			}
			set
			{
				this._ReporteNiñosPorJardin.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Jardin_Usuario", Storage="_Usuario", ThisKey="Identificador", OtherKey="IdentificadorJardin")]
		public EntitySet<Usuario> Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				this._Usuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Niño(Niño entity)
		{
			this.SendPropertyChanging();
			entity.Jardin = this;
		}
		
		private void detach_Niño(Niño entity)
		{
			this.SendPropertyChanging();
			entity.Jardin = null;
		}
		
		private void attach_ReporteJardinesNoAprobados(ReporteJardinesNoAprobados entity)
		{
			this.SendPropertyChanging();
			entity.Jardin = this;
		}
		
		private void detach_ReporteJardinesNoAprobados(ReporteJardinesNoAprobados entity)
		{
			this.SendPropertyChanging();
			entity.Jardin = null;
		}
		
		private void attach_ReporteNiñosPorJardin(ReporteNiñosPorJardin entity)
		{
			this.SendPropertyChanging();
			entity.Jardin = this;
		}
		
		private void detach_ReporteNiñosPorJardin(ReporteNiñosPorJardin entity)
		{
			this.SendPropertyChanging();
			entity.Jardin = null;
		}
		
		private void attach_Usuario(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Jardin = this;
		}
		
		private void detach_Usuario(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Jardin = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MadreComunitaria")]
	public partial class MadreComunitaria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Identificacion;
		
		private string _Nombres;
		
		private string _Telefono;
		
		private string _DireccionResidencia;
		
		private System.Nullable<System.DateTime> _FechaNacimiento;
		
		private EntitySet<Niño> _Niño;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdentificacionChanging(int value);
    partial void OnIdentificacionChanged();
    partial void OnNombresChanging(string value);
    partial void OnNombresChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnDireccionResidenciaChanging(string value);
    partial void OnDireccionResidenciaChanged();
    partial void OnFechaNacimientoChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaNacimientoChanged();
    #endregion
		
		public MadreComunitaria()
		{
			this._Niño = new EntitySet<Niño>(new Action<Niño>(this.attach_Niño), new Action<Niño>(this.detach_Niño));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identificacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Identificacion
		{
			get
			{
				return this._Identificacion;
			}
			set
			{
				if ((this._Identificacion != value))
				{
					this.OnIdentificacionChanging(value);
					this.SendPropertyChanging();
					this._Identificacion = value;
					this.SendPropertyChanged("Identificacion");
					this.OnIdentificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(100)")]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this.OnNombresChanging(value);
					this.SendPropertyChanging();
					this._Nombres = value;
					this.SendPropertyChanged("Nombres");
					this.OnNombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(20)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DireccionResidencia", DbType="VarChar(100)")]
		public string DireccionResidencia
		{
			get
			{
				return this._DireccionResidencia;
			}
			set
			{
				if ((this._DireccionResidencia != value))
				{
					this.OnDireccionResidenciaChanging(value);
					this.SendPropertyChanging();
					this._DireccionResidencia = value;
					this.SendPropertyChanged("DireccionResidencia");
					this.OnDireccionResidenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="Date")]
		public System.Nullable<System.DateTime> FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this.OnFechaNacimientoChanging(value);
					this.SendPropertyChanging();
					this._FechaNacimiento = value;
					this.SendPropertyChanged("FechaNacimiento");
					this.OnFechaNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MadreComunitaria_Niño", Storage="_Niño", ThisKey="Identificacion", OtherKey="IdentificadorMadre")]
		public EntitySet<Niño> Niño
		{
			get
			{
				return this._Niño;
			}
			set
			{
				this._Niño.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Niño(Niño entity)
		{
			this.SendPropertyChanging();
			entity.MadreComunitaria = this;
		}
		
		private void detach_Niño(Niño entity)
		{
			this.SendPropertyChanging();
			entity.MadreComunitaria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Niño")]
	public partial class Niño : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NIUP;
		
		private string _Nombre;
		
		private System.Nullable<System.DateTime> _FechaNacimiento;
		
		private string _TipoSangre;
		
		private string _CiudadNacimiento;
		
		private System.Nullable<int> _IdentificacionAcudiente;
		
		private string _Telefono;
		
		private string _Direccion;
		
		private string _EPS;
		
		private System.Nullable<int> _IdentificadorJardin;
		
		private System.Nullable<int> _IdentificadorAcudiente;
		
		private System.Nullable<int> _IdentificadorMadre;
		
		private System.Nullable<int> _IdentificadorUsuario;
		
		private EntitySet<Asistencia> _Asistencia;
		
		private EntitySet<AvanceAcademico> _AvanceAcademico;
		
		private EntitySet<Cumpleaños> _Cumpleaños;
		
		private EntitySet<ReporteInasistenciasEnfermedad> _ReporteInasistenciasEnfermedad;
		
		private EntitySet<ReporteSemanalAsistencia> _ReporteSemanalAsistencia;
		
		private EntityRef<Acudiente> _Acudiente;
		
		private EntityRef<Jardin> _Jardin;
		
		private EntityRef<MadreComunitaria> _MadreComunitaria;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNIUPChanging(int value);
    partial void OnNIUPChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnFechaNacimientoChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaNacimientoChanged();
    partial void OnTipoSangreChanging(string value);
    partial void OnTipoSangreChanged();
    partial void OnCiudadNacimientoChanging(string value);
    partial void OnCiudadNacimientoChanged();
    partial void OnIdentificacionAcudienteChanging(System.Nullable<int> value);
    partial void OnIdentificacionAcudienteChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnEPSChanging(string value);
    partial void OnEPSChanged();
    partial void OnIdentificadorJardinChanging(System.Nullable<int> value);
    partial void OnIdentificadorJardinChanged();
    partial void OnIdentificadorAcudienteChanging(System.Nullable<int> value);
    partial void OnIdentificadorAcudienteChanged();
    partial void OnIdentificadorMadreChanging(System.Nullable<int> value);
    partial void OnIdentificadorMadreChanged();
    partial void OnIdentificadorUsuarioChanging(System.Nullable<int> value);
    partial void OnIdentificadorUsuarioChanged();
    #endregion
		
		public Niño()
		{
			this._Asistencia = new EntitySet<Asistencia>(new Action<Asistencia>(this.attach_Asistencia), new Action<Asistencia>(this.detach_Asistencia));
			this._AvanceAcademico = new EntitySet<AvanceAcademico>(new Action<AvanceAcademico>(this.attach_AvanceAcademico), new Action<AvanceAcademico>(this.detach_AvanceAcademico));
			this._Cumpleaños = new EntitySet<Cumpleaños>(new Action<Cumpleaños>(this.attach_Cumpleaños), new Action<Cumpleaños>(this.detach_Cumpleaños));
			this._ReporteInasistenciasEnfermedad = new EntitySet<ReporteInasistenciasEnfermedad>(new Action<ReporteInasistenciasEnfermedad>(this.attach_ReporteInasistenciasEnfermedad), new Action<ReporteInasistenciasEnfermedad>(this.detach_ReporteInasistenciasEnfermedad));
			this._ReporteSemanalAsistencia = new EntitySet<ReporteSemanalAsistencia>(new Action<ReporteSemanalAsistencia>(this.attach_ReporteSemanalAsistencia), new Action<ReporteSemanalAsistencia>(this.detach_ReporteSemanalAsistencia));
			this._Acudiente = default(EntityRef<Acudiente>);
			this._Jardin = default(EntityRef<Jardin>);
			this._MadreComunitaria = default(EntityRef<MadreComunitaria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIUP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int NIUP
		{
			get
			{
				return this._NIUP;
			}
			set
			{
				if ((this._NIUP != value))
				{
					this.OnNIUPChanging(value);
					this.SendPropertyChanging();
					this._NIUP = value;
					this.SendPropertyChanged("NIUP");
					this.OnNIUPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="Date")]
		public System.Nullable<System.DateTime> FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this.OnFechaNacimientoChanging(value);
					this.SendPropertyChanging();
					this._FechaNacimiento = value;
					this.SendPropertyChanged("FechaNacimiento");
					this.OnFechaNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoSangre", DbType="VarChar(10)")]
		public string TipoSangre
		{
			get
			{
				return this._TipoSangre;
			}
			set
			{
				if ((this._TipoSangre != value))
				{
					this.OnTipoSangreChanging(value);
					this.SendPropertyChanging();
					this._TipoSangre = value;
					this.SendPropertyChanged("TipoSangre");
					this.OnTipoSangreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CiudadNacimiento", DbType="VarChar(100)")]
		public string CiudadNacimiento
		{
			get
			{
				return this._CiudadNacimiento;
			}
			set
			{
				if ((this._CiudadNacimiento != value))
				{
					this.OnCiudadNacimientoChanging(value);
					this.SendPropertyChanging();
					this._CiudadNacimiento = value;
					this.SendPropertyChanged("CiudadNacimiento");
					this.OnCiudadNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdentificacionAcudiente", DbType="Int")]
		public System.Nullable<int> IdentificacionAcudiente
		{
			get
			{
				return this._IdentificacionAcudiente;
			}
			set
			{
				if ((this._IdentificacionAcudiente != value))
				{
					this.OnIdentificacionAcudienteChanging(value);
					this.SendPropertyChanging();
					this._IdentificacionAcudiente = value;
					this.SendPropertyChanged("IdentificacionAcudiente");
					this.OnIdentificacionAcudienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(20)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(100)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EPS", DbType="VarChar(100)")]
		public string EPS
		{
			get
			{
				return this._EPS;
			}
			set
			{
				if ((this._EPS != value))
				{
					this.OnEPSChanging(value);
					this.SendPropertyChanging();
					this._EPS = value;
					this.SendPropertyChanged("EPS");
					this.OnEPSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdentificadorJardin", DbType="Int")]
		public System.Nullable<int> IdentificadorJardin
		{
			get
			{
				return this._IdentificadorJardin;
			}
			set
			{
				if ((this._IdentificadorJardin != value))
				{
					if (this._Jardin.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdentificadorJardinChanging(value);
					this.SendPropertyChanging();
					this._IdentificadorJardin = value;
					this.SendPropertyChanged("IdentificadorJardin");
					this.OnIdentificadorJardinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdentificadorAcudiente", DbType="Int")]
		public System.Nullable<int> IdentificadorAcudiente
		{
			get
			{
				return this._IdentificadorAcudiente;
			}
			set
			{
				if ((this._IdentificadorAcudiente != value))
				{
					if (this._Acudiente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdentificadorAcudienteChanging(value);
					this.SendPropertyChanging();
					this._IdentificadorAcudiente = value;
					this.SendPropertyChanged("IdentificadorAcudiente");
					this.OnIdentificadorAcudienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdentificadorMadre", DbType="Int")]
		public System.Nullable<int> IdentificadorMadre
		{
			get
			{
				return this._IdentificadorMadre;
			}
			set
			{
				if ((this._IdentificadorMadre != value))
				{
					if (this._MadreComunitaria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdentificadorMadreChanging(value);
					this.SendPropertyChanging();
					this._IdentificadorMadre = value;
					this.SendPropertyChanged("IdentificadorMadre");
					this.OnIdentificadorMadreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdentificadorUsuario", DbType="Int")]
		public System.Nullable<int> IdentificadorUsuario
		{
			get
			{
				return this._IdentificadorUsuario;
			}
			set
			{
				if ((this._IdentificadorUsuario != value))
				{
					this.OnIdentificadorUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdentificadorUsuario = value;
					this.SendPropertyChanged("IdentificadorUsuario");
					this.OnIdentificadorUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Niño_Asistencia", Storage="_Asistencia", ThisKey="NIUP", OtherKey="IdentificacionNiño")]
		public EntitySet<Asistencia> Asistencia
		{
			get
			{
				return this._Asistencia;
			}
			set
			{
				this._Asistencia.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Niño_AvanceAcademico", Storage="_AvanceAcademico", ThisKey="NIUP", OtherKey="IdentificacionNiño")]
		public EntitySet<AvanceAcademico> AvanceAcademico
		{
			get
			{
				return this._AvanceAcademico;
			}
			set
			{
				this._AvanceAcademico.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Niño_Cumpleaños", Storage="_Cumpleaños", ThisKey="NIUP", OtherKey="IdentificacionNiño")]
		public EntitySet<Cumpleaños> Cumpleaños
		{
			get
			{
				return this._Cumpleaños;
			}
			set
			{
				this._Cumpleaños.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Niño_ReporteInasistenciasEnfermedad", Storage="_ReporteInasistenciasEnfermedad", ThisKey="NIUP", OtherKey="IdentificacionNiño")]
		public EntitySet<ReporteInasistenciasEnfermedad> ReporteInasistenciasEnfermedad
		{
			get
			{
				return this._ReporteInasistenciasEnfermedad;
			}
			set
			{
				this._ReporteInasistenciasEnfermedad.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Niño_ReporteSemanalAsistencia", Storage="_ReporteSemanalAsistencia", ThisKey="NIUP", OtherKey="IdentificacionNiño")]
		public EntitySet<ReporteSemanalAsistencia> ReporteSemanalAsistencia
		{
			get
			{
				return this._ReporteSemanalAsistencia;
			}
			set
			{
				this._ReporteSemanalAsistencia.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Acudiente_Niño", Storage="_Acudiente", ThisKey="IdentificadorAcudiente", OtherKey="Identificacion", IsForeignKey=true)]
		public Acudiente Acudiente
		{
			get
			{
				return this._Acudiente.Entity;
			}
			set
			{
				Acudiente previousValue = this._Acudiente.Entity;
				if (((previousValue != value) 
							|| (this._Acudiente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Acudiente.Entity = null;
						previousValue.Niño.Remove(this);
					}
					this._Acudiente.Entity = value;
					if ((value != null))
					{
						value.Niño.Add(this);
						this._IdentificadorAcudiente = value.Identificacion;
					}
					else
					{
						this._IdentificadorAcudiente = default(Nullable<int>);
					}
					this.SendPropertyChanged("Acudiente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Jardin_Niño", Storage="_Jardin", ThisKey="IdentificadorJardin", OtherKey="Identificador", IsForeignKey=true)]
		public Jardin Jardin
		{
			get
			{
				return this._Jardin.Entity;
			}
			set
			{
				Jardin previousValue = this._Jardin.Entity;
				if (((previousValue != value) 
							|| (this._Jardin.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Jardin.Entity = null;
						previousValue.Niño.Remove(this);
					}
					this._Jardin.Entity = value;
					if ((value != null))
					{
						value.Niño.Add(this);
						this._IdentificadorJardin = value.Identificador;
					}
					else
					{
						this._IdentificadorJardin = default(Nullable<int>);
					}
					this.SendPropertyChanged("Jardin");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MadreComunitaria_Niño", Storage="_MadreComunitaria", ThisKey="IdentificadorMadre", OtherKey="Identificacion", IsForeignKey=true)]
		public MadreComunitaria MadreComunitaria
		{
			get
			{
				return this._MadreComunitaria.Entity;
			}
			set
			{
				MadreComunitaria previousValue = this._MadreComunitaria.Entity;
				if (((previousValue != value) 
							|| (this._MadreComunitaria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MadreComunitaria.Entity = null;
						previousValue.Niño.Remove(this);
					}
					this._MadreComunitaria.Entity = value;
					if ((value != null))
					{
						value.Niño.Add(this);
						this._IdentificadorMadre = value.Identificacion;
					}
					else
					{
						this._IdentificadorMadre = default(Nullable<int>);
					}
					this.SendPropertyChanged("MadreComunitaria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Asistencia(Asistencia entity)
		{
			this.SendPropertyChanging();
			entity.Niño = this;
		}
		
		private void detach_Asistencia(Asistencia entity)
		{
			this.SendPropertyChanging();
			entity.Niño = null;
		}
		
		private void attach_AvanceAcademico(AvanceAcademico entity)
		{
			this.SendPropertyChanging();
			entity.Niño = this;
		}
		
		private void detach_AvanceAcademico(AvanceAcademico entity)
		{
			this.SendPropertyChanging();
			entity.Niño = null;
		}
		
		private void attach_Cumpleaños(Cumpleaños entity)
		{
			this.SendPropertyChanging();
			entity.Niño = this;
		}
		
		private void detach_Cumpleaños(Cumpleaños entity)
		{
			this.SendPropertyChanging();
			entity.Niño = null;
		}
		
		private void attach_ReporteInasistenciasEnfermedad(ReporteInasistenciasEnfermedad entity)
		{
			this.SendPropertyChanging();
			entity.Niño = this;
		}
		
		private void detach_ReporteInasistenciasEnfermedad(ReporteInasistenciasEnfermedad entity)
		{
			this.SendPropertyChanging();
			entity.Niño = null;
		}
		
		private void attach_ReporteSemanalAsistencia(ReporteSemanalAsistencia entity)
		{
			this.SendPropertyChanging();
			entity.Niño = this;
		}
		
		private void detach_ReporteSemanalAsistencia(ReporteSemanalAsistencia entity)
		{
			this.SendPropertyChanging();
			entity.Niño = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReporteInasistenciasEnfermedad")]
	public partial class ReporteInasistenciasEnfermedad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _IdentificacionNiño;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private string _Reporte;
		
		private EntityRef<Niño> _Niño;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdentificacionNiñoChanging(System.Nullable<int> value);
    partial void OnIdentificacionNiñoChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    partial void OnReporteChanging(string value);
    partial void OnReporteChanged();
    #endregion
		
		public ReporteInasistenciasEnfermedad()
		{
			this._Niño = default(EntityRef<Niño>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdentificacionNiño", DbType="Int")]
		public System.Nullable<int> IdentificacionNiño
		{
			get
			{
				return this._IdentificacionNiño;
			}
			set
			{
				if ((this._IdentificacionNiño != value))
				{
					if (this._Niño.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdentificacionNiñoChanging(value);
					this.SendPropertyChanging();
					this._IdentificacionNiño = value;
					this.SendPropertyChanged("IdentificacionNiño");
					this.OnIdentificacionNiñoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reporte", DbType="VarChar(MAX)")]
		public string Reporte
		{
			get
			{
				return this._Reporte;
			}
			set
			{
				if ((this._Reporte != value))
				{
					this.OnReporteChanging(value);
					this.SendPropertyChanging();
					this._Reporte = value;
					this.SendPropertyChanged("Reporte");
					this.OnReporteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Niño_ReporteInasistenciasEnfermedad", Storage="_Niño", ThisKey="IdentificacionNiño", OtherKey="NIUP", IsForeignKey=true)]
		public Niño Niño
		{
			get
			{
				return this._Niño.Entity;
			}
			set
			{
				Niño previousValue = this._Niño.Entity;
				if (((previousValue != value) 
							|| (this._Niño.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Niño.Entity = null;
						previousValue.ReporteInasistenciasEnfermedad.Remove(this);
					}
					this._Niño.Entity = value;
					if ((value != null))
					{
						value.ReporteInasistenciasEnfermedad.Add(this);
						this._IdentificacionNiño = value.NIUP;
					}
					else
					{
						this._IdentificacionNiño = default(Nullable<int>);
					}
					this.SendPropertyChanged("Niño");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReporteJardinesNoAprobados")]
	public partial class ReporteJardinesNoAprobados : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _IdentificadorJardin;
		
		private string _Reporte;
		
		private EntityRef<Jardin> _Jardin;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdentificadorJardinChanging(System.Nullable<int> value);
    partial void OnIdentificadorJardinChanged();
    partial void OnReporteChanging(string value);
    partial void OnReporteChanged();
    #endregion
		
		public ReporteJardinesNoAprobados()
		{
			this._Jardin = default(EntityRef<Jardin>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdentificadorJardin", DbType="Int")]
		public System.Nullable<int> IdentificadorJardin
		{
			get
			{
				return this._IdentificadorJardin;
			}
			set
			{
				if ((this._IdentificadorJardin != value))
				{
					if (this._Jardin.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdentificadorJardinChanging(value);
					this.SendPropertyChanging();
					this._IdentificadorJardin = value;
					this.SendPropertyChanged("IdentificadorJardin");
					this.OnIdentificadorJardinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reporte", DbType="VarChar(MAX)")]
		public string Reporte
		{
			get
			{
				return this._Reporte;
			}
			set
			{
				if ((this._Reporte != value))
				{
					this.OnReporteChanging(value);
					this.SendPropertyChanging();
					this._Reporte = value;
					this.SendPropertyChanged("Reporte");
					this.OnReporteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Jardin_ReporteJardinesNoAprobados", Storage="_Jardin", ThisKey="IdentificadorJardin", OtherKey="Identificador", IsForeignKey=true)]
		public Jardin Jardin
		{
			get
			{
				return this._Jardin.Entity;
			}
			set
			{
				Jardin previousValue = this._Jardin.Entity;
				if (((previousValue != value) 
							|| (this._Jardin.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Jardin.Entity = null;
						previousValue.ReporteJardinesNoAprobados.Remove(this);
					}
					this._Jardin.Entity = value;
					if ((value != null))
					{
						value.ReporteJardinesNoAprobados.Add(this);
						this._IdentificadorJardin = value.Identificador;
					}
					else
					{
						this._IdentificadorJardin = default(Nullable<int>);
					}
					this.SendPropertyChanged("Jardin");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReporteNiñosPorJardin")]
	public partial class ReporteNiñosPorJardin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _IdentificadorJardin;
		
		private string _Reporte;
		
		private EntityRef<Jardin> _Jardin;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdentificadorJardinChanging(System.Nullable<int> value);
    partial void OnIdentificadorJardinChanged();
    partial void OnReporteChanging(string value);
    partial void OnReporteChanged();
    #endregion
		
		public ReporteNiñosPorJardin()
		{
			this._Jardin = default(EntityRef<Jardin>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdentificadorJardin", DbType="Int")]
		public System.Nullable<int> IdentificadorJardin
		{
			get
			{
				return this._IdentificadorJardin;
			}
			set
			{
				if ((this._IdentificadorJardin != value))
				{
					if (this._Jardin.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdentificadorJardinChanging(value);
					this.SendPropertyChanging();
					this._IdentificadorJardin = value;
					this.SendPropertyChanged("IdentificadorJardin");
					this.OnIdentificadorJardinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reporte", DbType="VarChar(MAX)")]
		public string Reporte
		{
			get
			{
				return this._Reporte;
			}
			set
			{
				if ((this._Reporte != value))
				{
					this.OnReporteChanging(value);
					this.SendPropertyChanging();
					this._Reporte = value;
					this.SendPropertyChanged("Reporte");
					this.OnReporteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Jardin_ReporteNiñosPorJardin", Storage="_Jardin", ThisKey="IdentificadorJardin", OtherKey="Identificador", IsForeignKey=true)]
		public Jardin Jardin
		{
			get
			{
				return this._Jardin.Entity;
			}
			set
			{
				Jardin previousValue = this._Jardin.Entity;
				if (((previousValue != value) 
							|| (this._Jardin.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Jardin.Entity = null;
						previousValue.ReporteNiñosPorJardin.Remove(this);
					}
					this._Jardin.Entity = value;
					if ((value != null))
					{
						value.ReporteNiñosPorJardin.Add(this);
						this._IdentificadorJardin = value.Identificador;
					}
					else
					{
						this._IdentificadorJardin = default(Nullable<int>);
					}
					this.SendPropertyChanged("Jardin");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReporteSemanalAsistencia")]
	public partial class ReporteSemanalAsistencia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _IdentificacionNiño;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private string _Reporte;
		
		private EntityRef<Niño> _Niño;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdentificacionNiñoChanging(System.Nullable<int> value);
    partial void OnIdentificacionNiñoChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    partial void OnReporteChanging(string value);
    partial void OnReporteChanged();
    #endregion
		
		public ReporteSemanalAsistencia()
		{
			this._Niño = default(EntityRef<Niño>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdentificacionNiño", DbType="Int")]
		public System.Nullable<int> IdentificacionNiño
		{
			get
			{
				return this._IdentificacionNiño;
			}
			set
			{
				if ((this._IdentificacionNiño != value))
				{
					if (this._Niño.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdentificacionNiñoChanging(value);
					this.SendPropertyChanging();
					this._IdentificacionNiño = value;
					this.SendPropertyChanged("IdentificacionNiño");
					this.OnIdentificacionNiñoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reporte", DbType="VarChar(MAX)")]
		public string Reporte
		{
			get
			{
				return this._Reporte;
			}
			set
			{
				if ((this._Reporte != value))
				{
					this.OnReporteChanging(value);
					this.SendPropertyChanging();
					this._Reporte = value;
					this.SendPropertyChanged("Reporte");
					this.OnReporteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Niño_ReporteSemanalAsistencia", Storage="_Niño", ThisKey="IdentificacionNiño", OtherKey="NIUP", IsForeignKey=true)]
		public Niño Niño
		{
			get
			{
				return this._Niño.Entity;
			}
			set
			{
				Niño previousValue = this._Niño.Entity;
				if (((previousValue != value) 
							|| (this._Niño.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Niño.Entity = null;
						previousValue.ReporteSemanalAsistencia.Remove(this);
					}
					this._Niño.Entity = value;
					if ((value != null))
					{
						value.ReporteSemanalAsistencia.Add(this);
						this._IdentificacionNiño = value.NIUP;
					}
					else
					{
						this._IdentificacionNiño = default(Nullable<int>);
					}
					this.SendPropertyChanged("Niño");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Identificacion;
		
		private string _Nombre;
		
		private string _Contraseña;
		
		private string _Rol;
		
		private System.Nullable<int> _IdentificadorJardin;
		
		private EntityRef<Jardin> _Jardin;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdentificacionChanging(int value);
    partial void OnIdentificacionChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnContraseñaChanging(string value);
    partial void OnContraseñaChanged();
    partial void OnRolChanging(string value);
    partial void OnRolChanged();
    partial void OnIdentificadorJardinChanging(System.Nullable<int> value);
    partial void OnIdentificadorJardinChanged();
    #endregion
		
		public Usuario()
		{
			this._Jardin = default(EntityRef<Jardin>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identificacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Identificacion
		{
			get
			{
				return this._Identificacion;
			}
			set
			{
				if ((this._Identificacion != value))
				{
					this.OnIdentificacionChanging(value);
					this.SendPropertyChanging();
					this._Identificacion = value;
					this.SendPropertyChanged("Identificacion");
					this.OnIdentificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="VarChar(100)")]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this.OnContraseñaChanging(value);
					this.SendPropertyChanging();
					this._Contraseña = value;
					this.SendPropertyChanged("Contraseña");
					this.OnContraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol", DbType="VarChar(20)")]
		public string Rol
		{
			get
			{
				return this._Rol;
			}
			set
			{
				if ((this._Rol != value))
				{
					this.OnRolChanging(value);
					this.SendPropertyChanging();
					this._Rol = value;
					this.SendPropertyChanged("Rol");
					this.OnRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdentificadorJardin", DbType="Int")]
		public System.Nullable<int> IdentificadorJardin
		{
			get
			{
				return this._IdentificadorJardin;
			}
			set
			{
				if ((this._IdentificadorJardin != value))
				{
					if (this._Jardin.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdentificadorJardinChanging(value);
					this.SendPropertyChanging();
					this._IdentificadorJardin = value;
					this.SendPropertyChanged("IdentificadorJardin");
					this.OnIdentificadorJardinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Jardin_Usuario", Storage="_Jardin", ThisKey="IdentificadorJardin", OtherKey="Identificador", IsForeignKey=true)]
		public Jardin Jardin
		{
			get
			{
				return this._Jardin.Entity;
			}
			set
			{
				Jardin previousValue = this._Jardin.Entity;
				if (((previousValue != value) 
							|| (this._Jardin.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Jardin.Entity = null;
						previousValue.Usuario.Remove(this);
					}
					this._Jardin.Entity = value;
					if ((value != null))
					{
						value.Usuario.Add(this);
						this._IdentificadorJardin = value.Identificador;
					}
					else
					{
						this._IdentificadorJardin = default(Nullable<int>);
					}
					this.SendPropertyChanged("Jardin");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
